author: hzhyang # 作者
description: hzhyang's blog
keyword: hexo-theme, vuejs
favicon: /css/images/blogfavicon.png

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: hzhyang
gitment_repo: hzhyang.github.io
gitment_oauth_id: bfe9d4d97fb413f8c217
gitment_oauth_secret: 5b8abf8205a8baf7519da4266bfdb50f8def8652

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://i.postimg.cc/mr8ykcFL/blog.png
  description: "我见青山多妩媚, 料青山见我应如是."
  #weibo_username: yanm1ng
  #twitter_username: yanm1ng
  github_username: hzhyang
  #zhihu_username: yummy1121
  #douban_username: yanm1ng
  #linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
